apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
        - name: spring-kubernetes-oomkilled
          image: spring-kubernetes-oomkilled-tutorial:latest  # Local image name
          imagePullPolicy: Never  # Prevent pulling the image from a registry
          resources:
            limits:
              memory: "128Mi"  # Set a low memory limit to trigger OOMKilled
          ports:
            - containerPort: 8080  # Expose the application on port 8080
---
apiVersion: v1
kind: Service
metadata:
  name: memory-hog-service
spec:
  selector:
    app: memory-hog
  ports:
    - protocol: TCP
      port: 8080  # The port that the service will expose
      targetPort: 8080  # The port the container listens on
  type: ClusterIP  # Default service type
